Combine store and store email tables
blueimpact/kucipong pull request #140
Opened 2017-03-06 12:06 UTC by cdepillabout

This PR gets rid of the `store_email` table and just uses the `store` table.

It also fixes the error from #113 where the Admin user is not able to delete a Store user unless the Store user has already been verified.

If this PR gets merged in to `master`, then the following SQL commands must be run:

```sql
drop table coupon cascade;
drop table store_login_token cascade;
drop table store cascade;
drop table store_email cascade;
```

2017-03-06 13:04 UTC, arowM requested changes
It apparently successed to create new store and immediately delete the store without verifying the store.
(I entered "(no store name)" to confirm delete as the confirm page required.)

But after the operation, DB table named `store` and `store_login_token` still have information about created email address in the previous step.

It causes following situation.

1. It fails to create a new store with the email address, I was redirected to a simple page that only sais "Internal Server Error".
    * In this time, server log says
    > Spock Error while handling ["admin","store","create"]: SqlError {sqlState = "23505", sqlExecStatus = FatalError, sqlErrorMsg = "duplicate key value violates unique constraint \"store_pkey\"", sqlErrorDetail = "Key (email)=(xxxxxxxxxx@gmail.com) already exists.", sqlErrorHint = ""}
2. It fails to delete the store with registered email address, then the page says "Could not find a store with that email address."

2017-03-06 13:04 UTC, arowM commented on frontend/src/pug/adminUser_admin_store_delete_confirm.pug
> +          input#defaultImage(
It's a trivial thing but `id` "defaultImage" is not suitable name.

2017-03-06 13:04 UTC, arowM commented on frontend/src/pug/storeUser_store.pug
> +                | \#{ label (fromMaybe Gourmet businessCategory) }
It might be better to use `minBound` like following for maintainability.

```haskell
label (fromMaybe minBound businessCategory)
```

2017-03-10 03:20 UTC, cdepillabout commented on frontend/src/pug/storeUser_store.pug
> +                | \#{ label (fromMaybe Gourmet businessCategory) }
This is a good idea, I'll fix this.

2017-03-10 03:21 UTC, cdepillabout commented on frontend/src/pug/adminUser_admin_store_delete_confirm.pug
> +          input#defaultImage(
Good catch, I think I missed this one.

2017-03-10 04:00 UTC, cdepillabout commented
Right now, the `Store`s, `Coupon`s, `Admin`s, etc are all being [logically deleted](http://stackoverflow.com/questions/378331/physical-vs-logical-soft-delete-of-database-record), not phsyically deleted.

Currently, a `Store`'s key is the email address for the `Store` user.  When a `Store` is deleted, all that happens is that it's `deleted_at` column gets updated from `null` to a date.  When trying to re-register a deleted `Store`, the email address conflicts (since it's the same as the email address for the `Store` that already exists in the database) and the error occurs.

Here are a couple ways we could fix this:

1.  Change the key of the `Store` table from the email address to a generic ID (probably an integer or UUID).
    - Since the key is no longer the email address, multiple `Store`s can be created that have the same email address.  In practice, we'd probably only want one non-deleted `Store` for each email address, but we could ignore deleted `Store`s.
2.  Instead of logically deleting `Store`s, we could physically delete them.
    - We'd also have to be sure to delete everything that uses a `Store` as a foreign key.  Right now I think this is just `Coupon`s.
    - We'd have to make sure that our database gets backed-up frequently.  We don't want an administration error to accidentally delete customer data.
3.  We could have a `StoreHistory` table and a `CouponHistory` table that records every change made to a `Store` or a `Coupon`.
    - This is like a  combination of (1) and (2).  It lets us keep a history while still being able to physically delete things.
4.  Switch to completely different storage paradigm, like [event sourcing](https://martinfowler.com/eaaDev/EventSourcing.html) or [datomic](http://www.datomic.com/).

---------------------------------

I think we should go with either (1) or (2).  I think either of them would be the easiest to implement and work with.

Personally, I think (3) is generally an anti-pattern.  If you want history information stored in the database, I think the best option is using event sourcing (4).  However, it would take us too much time to completely rewrite the database layer of Kucipong.  It would be interesting to try on a future project though ;-)

@arowM What do you think?

2017-03-10 04:07 UTC, cdepillabout commented
@arowM I've fixed the errors pointed out by the two comments in commit 6c3815c and d7bfe9a.  How about we merge this PR in, and figure out what to do about the `Store` key in a separate issue/PR?

2017-03-10 06:49 UTC, arowM commented
@cdepillabout 
Good! I'll merge this PR.
Could you create an issue to migrate to pattern (1) or (2), and create an separate issue to migrate to (4) with "low priority" label?
I'm also personally interested in some sort of "Immutable data structure".

2017-03-10 06:49 UTC, merged