Allow the store user to delete coupons.
blueimpact/kucipong pull request #155
Opened 2017-03-28 15:35 UTC by cdepillabout

This PR allows the `Store` user to delete `Coupon`s.

2017-03-28 15:47 UTC, cdepillabout commented
This fixes #133.

2017-03-29 13:42 UTC, arowM requested changes
Looks good!
If you resolved one trivial fix I commented, please go ahead and merge this in.

2017-03-29 13:42 UTC, arowM commented on src/Kucipong/Handler/Store/Coupon.hs
> +-- | Return the store create page for an admin.
Though it's trivial, this seems to be "Return the store delete page for an admin.".

2017-03-29 13:53 UTC, arowM commented
> 2. The coupon delete page looks a little funny. If you have any good ideas for making it look better, I'd appreciate it.

In the view point of [OOUX](https://www.sociomedia.co.jp/7279), it is better to provide a `X` button on each coupon of coupon list page (`/store/coupon`) instead of providing an independent coupon delete page. I'll do this change in future PR.
It should use Ajax, so I'm appreciate if you provide a JSON web API to delete a coupon with its coupon ID.

> 3. Since the coupon id template (frontend/src/pug/common/_coupon_id.pug) is the same for the end user and store user, I had to add an ugly hack to determine whether or not to show the coupon delete button. Can you think of any better way of doing this?

The way you did is not so bad, but I have better ways.
The point is we need not ask backend server to determine whether we should render delete button or not, but we can determine it in compile time.
So, I have two plan to realize this.
1. Add pug-side variable to handle appearance of delete button
2. Set the style of store delete button `display: block` in `store.scss`.
Anyway since I'll implement OOUX way of delete feature in future PR, then I'll change this, too.

2017-03-31 08:14 UTC, cdepillabout commented on src/Kucipong/Handler/Store/Coupon.hs
> +-- | Return the store create page for an admin.
This has been fixed in commit e0d576f.

2017-03-31 08:14 UTC, merged

2017-03-31 08:27 UTC, cdepillabout commented
Thanks for these two good ideas.  I've added issue #156 for me to implement the JSON API for deleting a coupon.  I've also added #157 for @arowM for adding the `X` button on each coupon.