Admin store create
blueimpact/kucipong pull request #16
Opened 2016-10-09 16:51 UTC by cdepillabout

This PR implements the admin store-create POST handler.

This PR also updates to lts-7 (ghc-8.0.1) in order to use the new http-api-data package for easily parsing http form data.

@arowM Please review.  Especially the `Kucipong.Db.Models.EntityDefs` module.  Let me know what you think.

Closes #9.  Closes #15.

2016-10-10 05:36 UTC, arowM requested changes
It's good generally.
But I've not still clearly realized why we use two tables (`Store` and `StoreEmail`) as store and not for admin user.

The followings are my comments for the questions in the code.

2016-10-10 05:36 UTC, arowM commented on src/Kucipong/Handler/Admin.hs
> +    -- TODO: Where to redirect this?
Redirect to the store create page, please.
I'll implement to show user as a pop up message on the page that the user has successfully created the store user, later.

2016-10-10 05:36 UTC, arowM commented on src/Kucipong/Spock/ReqParam.hs
> +        -- TODO: How should we handle this error?
Please make it possible to render any page template we want with errors as template parameters.
I'll implement later to show the errors as pop up message on the page.

2016-10-10 09:41 UTC, cdepillabout commented
@arowM Thanks for the review.

> I've not still clearly realized why we use two tables (`Store` and `StoreEmail`) as store and not for admin user.

When creating the `Admin` user, all the fields are known (both the email and the name of the admin user).  So there is no reason to split up the `Admin` table into two different tables.

But when creating the `Store` user, only the email is known.  So we split up the information about a store into two different tables, `StoreEmail` and `Store`.  Users that have been created in the database, but not actually logged in only exist in the `StoreEmail`.

As soon as the store user actually actually logs in and setups their store, then they also exist in the `Store` table.  Some of the fields in the `Store` table are required (like the name of the store, the category, etc).  But some fields are not required (like an image of the store).

This is similar to how we actually think about stores in real life.  It makes sense to only register emails for stores (but no other information) before the `Store` user actually logs in and sets up their store.  However, after the `Store` user logs in, it doesn't really make sense to have a `Store` with a name that can be `null`.  

My goal was to model the store tables similar to our real-life expectations about them.

However, it's entirely possible that this makes the `Store` table hard to actually use.  If we find out this is the case, then we should change them to your original design.

2016-10-10 09:42 UTC, cdepillabout commented on src/Kucipong/Handler/Admin.hs
> +    -- TODO: Where to redirect this?
Okay, I'll do this (and the next comment) next week :+1:

2016-10-10 12:04 UTC, arowM commented
@cdepillabout Thanks for detail explanation.  It makes sense.

2016-10-15 11:37 UTC, cdepillabout commented on src/Kucipong/Handler/Admin.hs
> +    -- TODO: Where to redirect this?
I fixed this in commit 3b49e2e.

2016-10-15 11:37 UTC, cdepillabout commented on src/Kucipong/Spock/ReqParam.hs
> +        -- TODO: How should we handle this error?
I will make a separate issue about this.

2016-10-15 11:38 UTC, cdepillabout commented
I will go ahead and merge this in.

One comment is not yet resolved, but I will create a separate issue about it.

2016-10-15 11:38 UTC, merged