Add the POST /store/coupon and GET /store/coupon/create handlers.
blueimpact/kucipong pull request #82
Opened 2016-12-26 14:56 UTC by cdepillabout

This is for issue #77.

2016-12-28 01:43 UTC, arowM commented
Thanks for renaming to readable variable name and fixing specification documents.

When I tried to create a coupon with `validFrom` on Chrome, the page show me an error bellow.

```
could not parse: `2016-12-14'
```

Even if I do not specify `validFrom` and `validUntil`, the page show me an error bellow.

```
could not parse: `'
```

Also, I've created extra issue related to this PR on #83 and #85.

2016-12-28 01:43 UTC, arowM requested changes
@cdepillabout 
Thanks for renaming to readable variable name and fixing specification documents.

When I tried to create a coupon with `validFrom` on Chrome, the page show me an error bellow.

```
could not parse: `2016-12-14'
```

Even if I do not specify `validFrom` and `validUntil`, the page show me an error bellow.

```
could not parse: `'
```

Also, I've created extra issue related to this PR on #83 and #85.

2016-12-28 01:43 UTC, arowM commented on frontend/src/pug/storeUser_store_coupon_id_edit.pug
> +                  value!='\#{fromMaybe "30" giftReferencePrice}'
The "30" I injected is just a sample.
If you do not have explicit reason to use "30" as a default value, please use `mempty` as default.
(Please fix line 117, 144, 153 as well as this line)

2017-01-02 14:29 UTC, cdepillabout commented
@arowM 
> When I tried to create a coupon with `validFrom` on Chrome, the page show me an error bellow.
>
> ```
> could not parse: `2016-12-14'
> ```

This has been fixed in commit ced7968.

> Even if I do not specify validFrom and validUntil, the page show me an error bellow.
>
> ```
> could not parse: `'
> ```

This has been fixed in commit 87b579c.

2017-01-02 14:38 UTC, cdepillabout commented on frontend/src/pug/storeUser_store_coupon_id_edit.pug
> +                  value!='\#{fromMaybe "30" giftReferencePrice}'
This is fixed in commit d289dfb.

2017-01-02 17:31 UTC, merged

2017-01-02 17:50 UTC, cdepillabout commented
I'll go ahead and merge this in.